apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-poc
  namespace: flux-config
spec:
  gitImplementation: libgit2
  interval: 1m
  url: https://github.com/Yearmix/flux-poc.git
  ref:
    branch: main
#  secretRef:
#   name: flux-config-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-poc
  namespace: flux-config
spec:
#  dependsOn:
#    - name: one
#    - name: two
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-poc
  path: ./apps
  prune: true
  wait: true
  timeout: 1m0s
  targetNamespace: flux-poc