apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 3
  template:
    metadata:
      name: test-app
      labels:
        app: test-app
    spec:
      containers:
      - image: olpotestacr.azurecr.io/olpotestacr/application-test-image:latest
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 8080